{% set name = "muler" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08f82719adf776b1c90a0bf1cc5299ee565d2dbd79b463d282a960daa5f62f5d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astropy >=4.1
    - specutils >=1.2
    - numpy 
    - scipy 
    - celerite2
    - gwcs >=0.17.1
    - pandas
    - matplotlib-base
    - h5py

test:
  imports:
    - muler

about:
  home: https://muler.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python package for working with pipeline-produced data from IGRINS and HPF'
  description: |
    muler is an easy to use Python package for post-processing echelle
    spectroscopy from near-infrared astronomical spectrographs.  We currently
    support IGRINS, HPF, and Keck NIRSPEC.
  doc_url: https://muler.readthedocs.io
  dev_url: https://github.com/OttoStruve/muler

extra:
  recipe-maintainers:
    - gully
