{% set name = "muler" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19c9c78cf6323ecc830b521d362f2c2d63c34758a225016f40e2e01ec7a01229

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astropy >=4.1
    - specutils >=1.2
    - numpy
    - scipy
    - celerite2
    - gwcs >=0.17.1
    - pandas
    - matplotlib-base
    - h5py

test:
  imports:
    - muler

about:
  home: https://muler.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for working with pipeline-produced data from IGRINS and HPF
  description: |
    muler is an easy to use Python package for post-processing echelle
    spectroscopy from near-infrared astronomical spectrographs.  We currently
    support IGRINS, HPF, and Keck NIRSPEC.
  doc_url: https://muler.readthedocs.io
  dev_url: https://github.com/OttoStruve/muler

extra:
  recipe-maintainers:
    - gully
